### ISSUE TITLE
Abstraction to run the ruby/node interpreter via the version manager

### ISSUE THREAD

**Issue by risen** [mina-deploy/mina-version_managers#2]
Hello,

I'd like to request some kind of abstraction to execute the right interpreter server-side.

The problem I'm trying to fix is the following (from one of my current projects):

```ruby
namespace :systemd do
  set :service_name, -> { fetch(:application_name) }

  desc 'Install systemd unit'
  task :setup do
    command %{mkdir -p "$HOME/.config/systemd/user"}

  end
    unit_file = <<-UNIT.gsub(/^ {6}/, '').strip
      [Unit]
      Description=Rails application server: #{fetch(:service_name)}
      After=network.target

      [Service]
      Type=simple
      Environment=RAILS_ENV=#{fetch(:rails_env)}
      EnvironmentFile=-#{fetch(:shared_path)}/.env
      WorkingDirectory=#{fetch(:current_path)}
      ExecStart=-/usr/bin/env #{'rbenv exec ' if fetch(:rbenv_path)}bundle exec puma --bind "unix://#{fetch(:shared_path)}/tmp/sockets/puma.sock" --config "#{fetch(:current_path)}/config/puma.rb" --control-url "unix://#{fetch(:shared_path)}/tmp/sockets/pumactl.sock" --pidfile "#{fetch(:shared_path)}/tmp/pids/puma.pid" --state "#{fetch(:shared_path)}/tmp/sockets/puma.state" --quiet
      Restart=always
      SyslogIdentifier=#{fetch(:service_name)}

      [Install]
      WantedBy=multi-user.target
    UNIT

    command %{echo #{Shellwords.escape(unit_file)} > "$HOME/.config/systemd/user/#{fetch(:service_name)}.service"}

    command %{systemctl --user daemon-reload}
    command %{systemctl --user enable #{fetch(:service_name)}.service}
  end
…
```

In case anyone's wondering: this unit doesn't use `Type=notify` or socket activation because of incompatibility with JRuby.

As you can tell, I had to hack around to ensure the `ExecStart` command line ends up being something like:

```ini
ExecStart=-/usr/bin/env rbenv exec bundle exec puma <bunch of options>
```

If I switch to another version manager, I would have to rewrite this too. It'd be nice if I could write:

```ruby
ExecStart=-#{fetch(:ruby_prefix)} puma <bunch of options>" 
```

…and that this would automatically work for rbenv, chruby, asdf, …

In addition:
* there should be a similar abstraction for node instead of ruby.
* there should (maybe) be something similar for bundler, yarn, npx, etc.

Thanks for your consideration.

**Comment by lovro-bikic** [comment]
That can be achieved by having tasks which set the `:ruby_prefix` variable with the desired value depending on the manager you want to use.

```ruby
task :with_rbenv do
  set :ruby_prefix, '/usr/bin/env rbenv exec bundle exec'
end

task :with_chruby do
  set :ruby_prefix, 'chruby ...'
end

task :with_asdf do
  set :ruby_prefix, 'asdf ...'
end
```

Your task `systemd:setup` can then use the `:ruby_prefix` variable like you wrote (`ExecStart=-#{fetch(:ruby_prefix)} puma <bunch of options>" `).

In the command-line, if you invoke `mina with_rbenv systemd:setup`, Mina would first set the `:ruby_prefix` variable and then execute `systemd:setup` with that value set.

If you're using a default manager and find it inconvenient to always have to invoke the task as `mina with_rbenv systemd:setup`, then you could do something like this:
```ruby
namespace :systemd do
  task :setup do
    invoke(:with_rbenv) unless set?(:ruby_prefix)
    
    # task contents
  end
end
```

With that, you can either use `mina systemd:setup` (which will default to rbenv), or you can override the manager by invoking `mina with_chruby systemd:setup`.
